### ISSUE TITLE
[FEATURE REQUEST] Distance Calculator

### ISSUE THREAD

**Issue by no4leafclover** [kumpeapps/UVT#5]
Would it be possible to add a simple conversion calculator within the UVT app that featured (foot to miles) / (miles to foot)? Would be easier to use one app instead to jumping to calculator to punch in the conversion when looking at troubleshooting distances. Thanks!

**Comment by justinkumpe** [comment]
That should not be too difficult. I'll look into getting that added.

**Comment by no4leafclover** [comment]
Thanks Justin!Sent from my iPhoneOn Apr 11, 2024, at 10:53 AM, Justin Kumpe ***@***.***> wrote:﻿
That should not be too difficult. I'll look into getting that added.

**Comment by justinkumpe** [comment]
This request has been added to the list for the 11.0 release. I was going to add it to a minor release but a bunch of frameworks have changed since my last release causing a bunch of issues that must be resoved before I can even build the existing app for testing or release. So I can not release anything with this app until I figure out what is causing all of the new errors. I already planned to do a complete redesign using Python and Flet so I will add this feature to that release as the re-design will be quicker than patching up the existing app. Current ETC is EOY.

**Comment by justinkumpe** [comment]
Distance Calculator has been added. I have submitted the new release to Google and Apple for review. Once they approve the app it will be available in their respective app stores.
